module.exports = {

    "Arunachal Pradesh": 83,
    "Assam": 65,
    "Bihar": 67,
    "Chhattisgarh": "67",
    "Chandigarh": 57,
    "Delhi": 48,
    "Goa": 60,
    "Gujarat": 65,
    "Haryana": 56,
    "Himachal Pradesh": 56,
    "Jammu and Kahmir": 65,
    "Jharkhand": 60,
    "Karnataka": 58.5,
    "Kerala": 60,
    "Madhya Pradesh": 60,
    "Maharashtra": 58.5,
    "Manipur": 65,
    "Meghalaya": 65,
    "Mizoram": 65,
    "Nagaland": 65,
    "Odisha": 67,
    "Pudducherry": 60,
    "Punjab": 57,
    "Rajasthan": 57,
    "Sikkim": 86.5,
    "Tamil Nadu": 59.5,
    "Telangana": 59.5,
    "Tripura": 71,
    "Uttar Pradesh": 48,
    "Uttarakhand": 57,
    "West Bengal": 60
}
